{{- $components := fromYaml (include "components" .) }}
{{- if and .Values.global.networkPolicy.enabled $components.synchronizer.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.synchronizer.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.synchronizer.name }}
    tier: {{ .Values.global.namespaceTier }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Values.synchronizer.name }}
      tier: {{ .Values.global.namespaceTier }}
  policyTypes:
    - Ingress
  {{- if .Values.global.networkPolicy.createEgressRules }}
    - Egress
  egress:
      # - synchronizer server
    - ports:
      - port: 443
        protocol: TCP
{{ tpl (.Files.Get "assets/common-egress-rules.yaml") . | indent 4 }}
  {{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/name: {{ .Values.nodeAgent.name }}
              tier: {{ .Values.global.namespaceTier }}
      ports:
        - port: {{ .Values.synchronizer.service.port }}
          protocol: TCP
{{- end }}
