{{- $components := fromYaml (include "components" .) }}
{{- $configurations := fromYaml (include "configurations" .) }}
{{- if and .Values.global.networkPolicy.enabled $components.otelCollector.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.otelCollector.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.otelCollector.name }}
    tier: {{ .Values.global.namespaceTier }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Values.otelCollector.name }}
      tier: {{ .Values.global.namespaceTier }}
  policyTypes:
    - Ingress
  {{- if .Values.global.networkPolicy.createEgressRules }}
    - Egress
  egress:
      # - otel backend
    - ports:
        - port: 443
          protocol: TCP
      {{- if $configurations.otel }}
        - port: {{ $configurations.otelPort }}
          protocol: TCP
      {{- end }}
{{ tpl (.Files.Get "assets/common-egress-rules.yaml") . | indent 4 }}
  {{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              otel: enabled
      ports:
        - port: otlp
          protocol: TCP
{{- end }}
