{{- $components := fromYaml (include "components" .) }}
{{- if $components.otelCollector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.otelCollector.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    kubescape.io/ignore: "true"
{{- end }}
