{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescapeScheduler.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.kubescapeScheduler.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubescapeScheduler.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
data:
  request-body.json: |-
    {"commands":[{"CommandName":"kubescapeScan","args":{"scanV1": {}}}]}
{{- end }}
