apiVersion: argoproj.io/v2.12.0-rc3
kind: Application
metadata:
  name: kubescape
  namespace: argocd # change to the argocd namespace
spec:
  destination:
    name: ''
    namespace: kubescape
    server: 'https://kubernetes.default.svc' # change to your server
  source:
    path: charts/kubescape-operator
    repoURL: 'https://github.com/kubescape/helm-charts'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: clusterName
          value: '' # add cluster name
          required: true
          type: string
        # Add adaptor server and account
        # - name: account
        #   value: '' # add account ID
        # - name: accessKey
        #   value: '' # add accessKey
        # - name: server
        #   value: '' # add Kubescape-compatible backend service URL
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated: 
      prune: false 
      selfHeal: true 
  ignoreDifferences:
    - group: core
      kind: ConfigMap
      name: ks-cloud-config
      namespace: kubescape
      jsonPointers:
        - /data
        - /metadata
