{{- $components := fromYaml (include "components" .) }}
{{- if $components.prometheusExporter.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheusExporter.name }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.prometheusExporter.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/ignore: "true"
rules:
  - apiGroups: ["spdx.softwarecomposition.kubescape.io"]
    resources: ["configurationscansummaries", "vulnerabilitysummaries"]
    verbs: ["get", "watch", "list"]
{{- end }}
