{{- $components := fromYaml (include "components" .) }}
{{- if and $components.storage.enabled .Values.global.openshift.scc.enabled }}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-scc" .Values.storage.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:    
    kubescape.io/ignore: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot-v2
subjects:
- kind: ServiceAccount
  name: {{ .Values.storage.name }}
  namespace: {{ .Values.ksNamespace }}
{{ end }}
