{{- $ca := genCA "kubescape-cluster-ca" 3650 }}
{{- $_ := set .Values.global "kubescapeCa" $ca.Cert -}}
{{- $cn := .Values.storage.name  }}
{{- $dns1 := printf "%s.%s" $cn .Values.ksNamespace }}
{{- $dns2 := printf "%s.%s.svc" $cn .Values.ksNamespace }}
{{- $dns3 := printf "%s.%s.svc.cluster.local" $cn .Values.ksNamespace }}

{{- $cert := genSignedCert $cn nil (list $dns1 $dns2 $dns3) 3650 $ca }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storage.name }}
  namespace: {{ .Values.ksNamespace }}
type: Opaque
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}