{{- $components := fromYaml (include "components" .) }}
{{- if $components.kollector.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.kollector.name }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kollector.name "tier" .Values.global.namespaceTier) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kollector.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kollector.name }}
  namespace: {{ .Values.ksNamespace }}
{{- end }}
