{{- $components := fromYaml (include "components" .) }}
{{- if $components.nodeAgent.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.nodeAgent.name }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.nodeAgent.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/ignore: "true"
subjects:
- kind: ServiceAccount
  name: {{ .Values.nodeAgent.name }}
  namespace: {{ .Values.ksNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.nodeAgent.name }}
{{- end }}
