{{- if and .Values.alertCRD.installDefault .Values.alertCRD.scopeClustered }}
apiVersion: kubescape.io/v1
kind: RuntimeRuleAlertBinding
metadata:
  name: all-rules-all-pods
spec:
  namespaceSelector:
    matchExpressions:
      {{- if ne .Values.includeNamespaces "" }}
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values:
          {{- $namespaces := split "," .Values.includeNamespaces }}
          {{- range $namespaces }}
          - {{ . | quote }}
          {{- end }}
      {{- else if ne .Values.excludeNamespaces "" }}
      - key: "kubernetes.io/metadata.name"
        operator: "NotIn"
        values:
          {{- $namespaces := split "," .Values.excludeNamespaces }}
          {{- range $namespaces }}
          - {{ . | quote }}
          {{- end }}
      {{- end }}
  rules:
    - ruleName: "Unexpected process launched"
    - ruleName: "Unexpected file access"
      parameters:
        ignoreMounts: true
        ignorePrefixes: ["/proc", "/run/secrets/kubernetes.io/serviceaccount", "/var/run/secrets/kubernetes.io/serviceaccount", "/tmp"]
    - ruleName: "Unexpected system call"
    - ruleName: "Unexpected capability used"
    - ruleName: "Unexpected domain request"
    - ruleName: "Unexpected Service Account Token Access"
    - ruleName: "Kubernetes Client Executed"
    - ruleName: "Exec from malicious source"
    - ruleName: "Kernel Module Load"
    - ruleName: "Exec Binary Not In Base Image"
    - ruleName: "Malicious SSH Connection"
    - ruleName: "Fileless Execution"
    - ruleName: "XMR Crypto Mining Detection"
    - ruleName: "Exec from mount"
    - ruleName: "Crypto Mining Related Port Communication"
    - ruleName: "Crypto Mining Domain Communication"
    - ruleName: "Read Environment Variables from procfs"
    - ruleName: "eBPF Program Load"
    - ruleName: "Symlink Created Over Sensitive File"
    - ruleName: "Unexpected Sensitive File Access"
    - ruleName: "LD_PRELOAD Hook"
    - ruleName: "Hardlink Created Over Sensitive File"
{{- end }}
