{{- $components := fromYaml (include "components" .) }}
{{- if $components.nodeAgent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodeAgent.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.nodeAgent.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/ignore: "true"
{{- end }}
