- ports:
    - port: 53
      protocol: UDP
  to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
- ports:
    - port: 4317
      protocol: TCP
  to:
    - podSelector:
        matchLabels:
          app: otel-collector
{{- if ne .Values.global.httpsProxy "" }}
- ports:
    - port: {{ .Values.global.networkPolicy.httpsProxyPort }}
      protocol: TCP
  to:
    - ipBlock:
        cidr: {{ .Values.global.networkPolicy.httpsProxyIP }}/32
{{- end }}
