{{- $components := fromYaml (include "components" .) }}
  {{- if $components.operator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
data:
  config.json: |
    {
        {{- if ne .Values.includeNamespaces "" }}
        "includeNamespaces": "{{ .Values.includeNamespaces }}",
        {{- else if ne .Values.excludeNamespaces "" }}
        "excludeNamespaces": "{{ .Values.excludeNamespaces }}",
        {{- end }}
        "namespace": "{{ .Values.ksNamespace }}",
        "triggersecurityframework": {{ .Values.operator.triggerSecurityFramework }},
        "httpExporterConfig": {{- .Values.nodeAgent.config.httpExporterConfig | toJson }}
    }
{{- end }}
