{{ $hookName := "label-selector-force-replace" -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $hookName }}
  namespace: {{ .Values.ksNamespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app: {{ $hookName }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - "delete"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $hookName }}
  namespace: {{ .Values.ksNamespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app: {{ $hookName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $hookName }}
  namespace: {{ .Values.ksNamespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-14"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app: {{ $hookName }}
subjects:
  - kind: ServiceAccount
    name: {{ $hookName }}
    namespace: {{ .Values.ksNamespace }}
roleRef:
  kind: Role
  name: {{ $hookName }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hookName }}
  namespace: {{ .Values.ksNamespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
  labels:
    app: {{ $hookName }}
spec:
  template:
    spec:
      serviceAccountName: {{ $hookName }}
      containers:
        - name: {{ $hookName }}
          image: "docker.io/bitnami/kubectl:1.30.3"
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/sh
            - -e
            - -x
            - -c
            - >-
              kubectl -n {{ .Values.ksNamespace }} delete daemonset node-agent --ignore-not-found=true;
              kubectl -n {{ .Values.ksNamespace }} delete deployment gateway --ignore-not-found=true;
              kubectl -n {{ .Values.ksNamespace }} delete deployment kubescape --ignore-not-found=true;
              kubectl -n {{ .Values.ksNamespace }} delete deployment kubevuln --ignore-not-found=true;
              kubectl -n {{ .Values.ksNamespace }} delete deployment operator --ignore-not-found=true;
              kubectl -n {{ .Values.ksNamespace }} delete deployment otel-collector --ignore-not-found=true;
              kubectl -n {{ .Values.ksNamespace }} delete deployment storage --ignore-not-found=true;
              kubectl -n {{ .Values.ksNamespace }} delete deployment synchronizer --ignore-not-found=true;
              kubectl -n {{ .Values.ksNamespace }} delete statefulset kollector --ignore-not-found=true;
      restartPolicy: Never
  backoffLimit: 6
