{{- $components := fromYaml (include "components" .) }}
{{- if $components.autoUpdater.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.ksNamespace }}
  name: {{ .Values.helmReleaseUpgrader.name }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    kubescape.io/ignore: "true"
{{ end }}
