{{- $components := fromYaml (include "components" .) }}
{{- if $components.autoUpdater.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.ksNamespace }}
  name: {{ .Values.helmReleaseUpgrader.name }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.helmReleaseUpgrader.name "tier" .Values.global.namespaceTier) | nindent 4 }}
{{ end }}
