{{- $components := fromYaml (include "components" .) }}
{{- if $components.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.gateway.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/ignore: "true"
spec:
  type: {{ .Values.gateway.httpService.type }}
  ports:
    - port: {{ .Values.gateway.websocketService.port }}
      targetPort: {{ .Values.gateway.websocketService.targetPort }}
      protocol: {{ .Values.gateway.websocketService.protocol }}
      name: "websocket"
    - port: {{ .Values.gateway.httpService.port }}
      targetPort: {{ .Values.gateway.httpService.targetPort }}
      protocol: {{ .Values.gateway.httpService.protocol }}
      name: "http"
  selector:
    {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.gateway.name) | nindent 4 }}
{{- end }}
