{{- $components := fromYaml (include "components" .) }}
{{- if $components.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" . | nindent 4 }}
    kubescape.io/ignore: "true"
{{- end }}
