{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubevuln.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubevuln.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubevuln.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/ignore: "true"
spec:
  type: {{ .Values.kubevuln.service.type }}
  ports:
    - port: {{ .Values.kubevuln.service.port }}
      targetPort: {{ .Values.kubevuln.service.targetPort }}
      protocol: {{ .Values.kubevuln.service.protocol }}
  selector:
    app: {{ .Values.kubevuln.name }}
{{- end }}
