{{- $components := fromYaml (include "components" .)  }}
{{- $configurations := fromYaml (include "configurations" .)  }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.global.cloudConfig }}
  namespace: {{ .Values.ksNamespace }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.global.cloudConfig "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
    kubescape.io/infra: config
data:
  clusterData: |
    {
      "serviceDiscovery": {{ $components.serviceDiscovery.enabled }},
      "vulnScanURL": "{{ .Values.kubevuln.name }}:{{ .Values.kubevuln.service.port }}",
      "kubevulnURL": "{{ .Values.kubevuln.name }}:{{ .Values.kubevuln.service.port }}",
      "kubescapeURL": "{{ .Values.kubescape.name }}:{{ .Values.kubescape.service.port }}",
      "clusterName": "{{ regexReplaceAll "\\W+" .Values.clusterName "-" }}",
      "storage": {{ $components.storage.enabled }},
      "relevantImageVulnerabilitiesEnabled": {{ eq .Values.capabilities.relevancy "enable" }},
      "namespace": "{{ .Values.ksNamespace }}",
      "imageVulnerabilitiesScanningEnabled": {{ $components.kubevuln.enabled }},
      "postureScanEnabled": {{ $components.kubescape.enabled }},
      "otelCollector": {{ $components.otelCollector.enabled }},
      "nodeAgent": "{{ $components.nodeAgent.enabled }}",
      "maxImageSize": {{ .Values.kubevuln.config.maxImageSize }},
      "maxSBOMSize": {{ .Values.kubevuln.config.maxSBOMSize }},
      "keepLocal": {{ not $components.serviceDiscovery.enabled }},
      "scanTimeout": "{{ .Values.kubevuln.config.scanTimeout }}",
      "scanEmbeddedSBOMs": {{ eq .Values.capabilities.scanEmbeddedSBOMs "enable" }},
      "vexGeneration": {{ eq .Values.capabilities.vexGeneration "enable" }},
      "useDefaultMatchers": {{ .Values.kubevuln.config.useDefaultMatchers }},
      "storeFilteredSbom": {{ or .Values.kubevuln.config.storeFilteredSboms (eq .Values.capabilities.syncSBOM "enable") }},
      "continuousPostureScan": {{ $configurations.continuousScan }},
{{- if not (empty .Values.kubevuln.config.grypeDbListingURL) }}
      "listingURL": "{{ .Values.kubevuln.config.grypeDbListingURL }}",
{{- end }}
{{- if .Values.grypeOfflineDB.enabled }}
      "listingURL": "http://{{ .Values.grypeOfflineDB.name }}:80/databases",
{{- end }}
      "relevantImageVulnerabilitiesConfiguration": "{{ .Values.capabilities.relevancy }}"
    }
