kind: ConfigMap
apiVersion: v1
metadata:
  name: ks-capabilities
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" . | nindent 4 }}
    app: ks-capabilities
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
data:
  capabilities: |
    {
      "capabilities": {{- .Values.capabilities | toJson }},
      "components": {{- include "components" . | fromYaml | toJson }},
      "configurations": {{- .Values.configurations | toJson }} ,
      "serviceScanConfig" : {{- .Values.serviceScanConfig | toJson }}
    }
