{{- if .Values.configurations.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubescape-critical
  labels:
    {{- include "kubescape-operator.labels" . | nindent 4 }}
value: {{ .Values.configurations.priorityClass.daemonset }}
globalDefault: false
description: "This priority class is for node-agent daemonset pods"
{{- end }}
