{{- if .Values.grypeOfflineDB.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grypeOfflineDB.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.grypeOfflineDB.name }}
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "kubescape-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.grypeOfflineDB.name }}
      tier: {{ .Values.global.namespaceTier }}
  template:
    metadata:
      labels:
        {{- include "kubescape-operator.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.grypeOfflineDB.name }}
        kubescape.io/tier: "core"
        tier: {{ .Values.global.namespaceTier }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ toYaml .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Values.grypeOfflineDB.name }}
          image: "{{ .Values.grypeOfflineDB.image.repository }}{{ if .Values.grypeOfflineDB.image.tag }}:{{ .Values.grypeOfflineDB.image.tag }}{{ else }}@{{ .Values.grypeOfflineDB.image.sha }}{{ end }}"
          imagePullPolicy: {{ .Values.grypeOfflineDB.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
{{ toYaml .Values.grypeOfflineDB.resources | indent 12 }}
      nodeSelector:
      {{- if .Values.grypeOfflineDB.nodeSelector }}
      {{- toYaml .Values.grypeOfflineDB.nodeSelector | nindent 8 }}
      {{- else if .Values.customScheduling.nodeSelector }}
      {{- toYaml .Values.customScheduling.nodeSelector | nindent 8 }}
      {{- end }}
      affinity:
      {{- if .Values.grypeOfflineDB.affinity }}
      {{- toYaml .Values.grypeOfflineDB.affinity | nindent 8 }}
      {{- else if .Values.customScheduling.affinity }}
      {{- toYaml .Values.customScheduling.affinity | nindent 8 }}
      {{- end }}
      tolerations:
      {{- if .Values.grypeOfflineDB.tolerations }}
      {{- toYaml .Values.grypeOfflineDB.tolerations | nindent 8 }}
      {{- else if .Values.customScheduling.tolerations }}
      {{- toYaml .Values.customScheduling.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
