{{- if .Values.grypeOfflineDB.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.grypeOfflineDB.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kubescape-operator.labels" . | nindent 4 }}
    app: {{ .Values.grypeOfflineDB.name }}
    tier: {{ .Values.global.namespaceTier }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Values.grypeOfflineDB.name }}
      app.kubernetes.io/component: {{ .Values.grypeOfflineDB.name }}
      tier: {{ .Values.global.namespaceTier }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/name: {{ .Values.kubevuln.name }}
              tier: {{ .Values.global.namespaceTier }}
      ports:
        - port: 8080
          protocol: TCP
{{- end }}
