name: Trigger performance test on Label Creation

on:
  pull_request:
    types:
      - labeled

jobs:
  trigger-performance-test:
    if: github.event.label.name == 'ready'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger performance Workflow on bump branch
        if: github.event.label.name == 'ready'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ secrets.PERFORM_REPO_TOKEN }}" \
               https://api.github.com/repos/armosec/perfornamce/actions/workflows/performance.yaml/dispatches \
               -d '{
                 "ref": "main",
                 "inputs": {
                   "CLUSTER_NAME": "perfo-cluster-for-release",
                   "NODE_SIZE": "s-8vcpu-16gb",
                   "NODE_COUNT": "40",
                   "DURATION_TIME": "240",
                   "KUBERNETES_VERSION": "",
                   "STORAGE_VERSION": "",
                   "NODE_AGENT_VERSION": "",
                   "ENABLE_KDR": false,
                   "PRIVATE_NODE_AGENT": "",
                   "HELM_GIT_BRANCH": "bump"
                 }
               }'
